### ISSUE TITLE
Ashita

### ISSUE THREAD

**Issue by MatthewJHBerry** [Hokuten85/XICamera#1]
It says the latest versions are for Windower only. The Ashita one is a couple versions back. When trying to use this in Ashita it says it's v3, expecting 3.10. Any solution to this?

**Comment by Hokuten85** [comment]
My repository is quite a mess >_< Was working on lua implementations at the beginning of the year.

I rebuilt the ashita 3 plugin version and added a new release. I loaded it up but didn't test it extensively.  There's also a bunch of the lua implementations in the release.

**Comment by Hokuten85** [comment]
https://github.com/Hokuten85/XICamera/releases/tag/0.6
