### ISSUE TITLE
Zoom distances past "/cam d 7" deafen proximity audio

### ISSUE THREAD

**Issue by 99jakari** [Hokuten85/XICamera#14]
On Ashita v4, using the latest XiCamera version (0.7.5) 
Camera distances beyond 7 seem to significantly affect the audio, causing it to get softer the further you go. This affects seems to affect all audio initiated by players/monsters/NPCs/etc.  

A small exception to this is when the camera sits at the floor level, the audio appears to be at it's loudest and can be heard from much further away distances, but still gets quieter the further out you zoom.

**Comment by Hokuten85** [comment]
Yeah, I've looked into this one and I've not found any obvious ways to fix it. Things are a bit busy, but I'll probably poke around a bit more with it this weekend and see what I can come up with.

**Comment by Hokuten85** [comment]
I've dropped a pre-release of an adjustment that seems to help with the audio, but it's still not perfect. Can at least hear at further camera distances, but eventually you get outside of the 30 yalm audio limit and it goes silent again. I found a memory location that increases that limit, but I'm not sure a good fix is to increase that.

https://github.com/Hokuten85/XICamera/releases/tag/v0.7.6
