### ISSUE TITLE
Failed to locate vPanSpeedSig on Horizon

### ISSUE THREAD

**Issue by samson-ffxi** [Hokuten85/XICamera#15]
After the client update on Horizon, the latest release of xicamera fails to load while trying to find the location of vPanSpeedSig.

Ashita v4
xicamera v0.7.8
FFXiMain.dll sha256 f4f90fbd080c05448aab3f866b127d7c1675b3cc15c8beaa57bfc584064b7e7c

![image](https://github.com/Hokuten85/XICamera/assets/130154563/a114c2b9-7431-4726-8c24-cf3e292f522e)

**Comment by Hokuten85** [comment]
I just fired up Horizon and loaded up the camera without getting this error.  Do you get this error from a fresh boot of the game? Or did you turn off version 0.7.6 and then try to load this one up?
I've had some inconsistencies with 0.7.6 not unloading cleanly, and borking up the memory location I'm looking for.  0.7.6 actually injected code at this point.
0.7.8 does no code injection so it should be better going forward.

**Comment by samson-ffxi** [comment]
It was from a clean start of the client.  I tried again just now and it is loading as expected this morning. 🤷  I'll keep an eye on it and reopen if it continues to crop up.
