### ISSUE TITLE
Lua runtime error after reinstall Windows 10 and FFXI

### ISSUE THREAD

**Issue by siuhamlop** [Hokuten85/XICamera#16]
![キャプチャ](https://github.com/user-attachments/assets/be458dc1-ac31-4901-ac9e-be872672007c)
After reinstall windows 10 and FFXI, XICamera not working coz of lua runtime error, the dll not load. I have installed almost all VSC++, please someone help.
![キャプチャ1](https://github.com/user-attachments/assets/b3865d56-12e0-4475-ba71-b1734c3d2115)

**Comment by Hokuten85** [comment]
https://aka.ms/vs/17/release/vc_redist.x64.exe

try this one. It's an install for 2015-2022. Looks like it will contain a few more years than what you have installed.

**Comment by siuhamlop** [comment]
After install the x86 version, it works now, thank you so much.
