### ISSUE TITLE
Interface version is not valid. Plugin 3.10. Expected 3.20

### ISSUE THREAD

**Issue by Lotharl** [Hokuten85/XICamera#3]
Using the Ashita plugin and I think the latest update of FFXI Retail is not compatible now?

"Failed to load plugin xicamera.dll. Interface version is not valid. Plugin 3.10. Expected 3.20."

Thanks!

**Comment by Hokuten85** [comment]
[Ashita.zip](https://github.com/Hokuten85/XICamera/files/8741941/Ashita.zip)

the project is a bit of a mess at the moment and I've been super lazy about cleaning it up.  I think the zip above should have a rebuild with the newer ashita interface. I'm not in a place where I can test this at the moment. Probably wont get to it until Sunday.

There is an addon version that shouldn't suffer from the changing ashita versions if you wanted to use that instead.

**Comment by Lotharl** [comment]
> 
Appreciate it, I'll try it out and report any issues if I find any :)

**Comment by Lotharl** [comment]
I'm experiencing the camera getting hooked onto the surrounding sometimes, like its getting stuck on the celling. You have to move a a certain distance away for it to snap back otherwise you can't control the camera.

**Comment by Hokuten85** [comment]
Yeah, this solution has issues with collision detection, and that's not something I'm going to put any time into. The plugin solution tries to inject code into the game at certain points to recalculate the position of the camera. It's certainly not perfect.

The addon solutions recalculate the position right before rendering. It's possible that those have less issues with the collision detection, though I've spent less time testing those versions.
