### ISSUE TITLE
xicamera v0.7 "status"

### ISSUE THREAD

**Issue by Heretic6667** [Hokuten85/XICamera#6]
seems the //xicamera status command is no longer working.  Nothing game breaking, but FYI  
![image](https://user-images.githubusercontent.com/65053603/208703139-c77d3dc3-ada3-4ecc-8efb-91d2f4905bb1.png)

**Comment by Hokuten85** [comment]
This is for the windower 4 version? I actually was intending to remove the function, but forgot to take it out of the lua file.  Do you think we still need to display a status? Mostly, it's just on or off.

**Comment by Heretic6667** [comment]
Yes, windower 4 version.

Is it a necessary command?  No, not really.  Honestly only used it to see my distance settings right before I updated to the latest version.

**Comment by Hokuten85** [comment]
I've removed the status command in the most recent release. I'm lazy. Sorry. I suppose I'll add it back if people yell at me.
