### ISSUE TITLE
XiCamera 0.7.1 NPCs walking funky

### ISSUE THREAD

**Issue by Heretic6667** [Hokuten85/XICamera#7]
Not sure if this started with 0.7 or 0.7.1, but certain NPCs that walked around at abnormal speeds look... off.  

Iron Muscles normally walks around the Rabao HP No.2 in slow-mo.  With the latest xicamera loaded (windower 4 version) he'll walk around like his framerate is uncapped.

Just funky to see.

**Comment by Hokuten85** [comment]
There was a move speed bug that I thought I fixed in a more recent version. I'll have to talk a look at it. Not playing retail anymore, so I'll have to see if I can fire up a private server so I can check out the npc

**Comment by Hokuten85** [comment]
I have a new release out that should fix the NPC run speed animation. 
https://github.com/Hokuten85/XICamera/releases/tag/v0.7.2

Let me know how it goes.

**Comment by Heretic6667** [comment]
Iron Muscles is back to normal :)

Thanks!
