### ISSUE TITLE
locked onto target, zoom amount reverts

### ISSUE THREAD

**Issue by koalatytimekoala** [Hokuten85/XICamera#8]
Hello, just updated to the new version of Xicamera for windower4 thank you for your work on this addon!

Only thing I noticed is that when I lock onto a target it zooms back in (to default?) instead of staying zoomed out compared to the older version that I've enjoyed for a while now. Thank you again!

**Comment by Hokuten85** [comment]
The new version uses a different mechanism that sort of easily separated the normal vs battle camera.  I added a command to set them independently.

/cam distance ##
/cam d ##
or
/cam battle ##
/cam b ##
