### ISSUE TITLE
min distance event error

### ISSUE THREAD

**Issue by zachkinsey** [Hokuten85/XICamera#9]
after addon is loaded it returns some error talking about 'min distance sig' or something like that. Can't remember atm.

**Comment by Hokuten85** [comment]
which version of the addon?  Playing on retail?

**Comment by zachkinsey** [comment]
latest version. Ashita 3 ( maybe 4 as well, can't remember ). Playing on Eden private server. It also happens on Horizionxi private server which uses Ashita 4.

**Comment by Hokuten85** [comment]
I wonder why its not able to find the signature for you on Horizon. That's the version I am working with to identify the memory locations. I'll redownload retail and see if that version might need a different/better signature.

Was it working on the previous releases? 0.7.2?  I didn't change the signature between 0.7.0 and 0.7.3.

**Comment by zachkinsey** [comment]
I can't remember what version it was working on as I recently had my OS SSD become unusable and had to reinstall everything since I didn't have a back up, but for reference, it was working when I initially got on horizion around Dec. 20th or so.

**Comment by Hokuten85** [comment]
can you attach the lua files that you are using so I can see if it's using the same signatures?

**Comment by zachkinsey** [comment]
[xicamera_ashita3_addon_v0.7.3.zip](https://github.com/Hokuten85/XICamera/files/10416309/xicamera_ashita3_addon_v0.7.3.zip)

Your latest release has the same issue.

In game it says, failed to call event load. Error: *path*.lua:106: Failed to located minDistanceSig

**Comment by Hokuten85** [comment]
can you give that a go in ashita 3 and let me know if it finds that minDistanceSig?  I might need to find different signatures for the other memory locations, but I want see if this works.

[xicamera.zip](https://github.com/Hokuten85/XICamera/files/10416573/xicamera.zip)

**Comment by Hokuten85** [comment]
https://github.com/Hokuten85/XICamera/releases/tag/v0.7.4

I'm going to close this. Hopefully the signatures are better.
